name: Lint, Test, Build

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "**"
  pull_request:

jobs:
  lint:
    uses: smallstep/workflows/.github/workflows/goLint.yml@main

  test:
    needs: lint
    uses: smallstep/workflows/.github/workflows/goTest.yml@main

  build:
    needs: test
    uses: smallstep/workflows/.github/workflows/goBuild.yml@main
